import type { Metadata } from "next";

import localFont from "next/font/local";
import { Saira } from "next/font/google";

import "./globals.css";

import NavbarDesktop from "@/components/navbar";
import { navigationItems } from "@/data/navbarItems";

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

const specialGothicExtendedBold = localFont({
  src: "../public/fonts/SpecialGothicExtendedBold.woff2",
  display: "swap",
  variable: "--font-special",
});

export const metadata: Metadata = {
  title: "ANTIKOR | Síla mýtu, preciznost stroje",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${saira.variable} ${specialGothicExtendedBold.variable} antialiased`}
      >
        <NavbarDesktop items={navigationItems} />
        {children}
      </body>
    </html>
  );
}
